#!/usr/bin/env bash
# Copies product.json to every consumer. Run after editing product.json.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/product.json"

mkdir -p "$ROOT/supabase/functions/_shared" "$ROOT/owner-app/src" "$ROOT/wall-app/Sources/Generated"
cp "$SRC" "$ROOT/supabase/functions/_shared/product.json"
cp "$SRC" "$ROOT/owner-app/src/product.json"

node - "$SRC" "$ROOT/wall-app/Sources/Generated/Product.swift" <<'JS'
const fs = require("fs");
const [src, out] = process.argv.slice(2);
const p = JSON.parse(fs.readFileSync(src, "utf8"));
const lines = ["// Generated by scripts/sync-product.sh from product.json. Do not edit.", "", "enum Product {"];
for (const [k, v] of Object.entries(p)) {
  if (typeof v === "string") lines.push(`    static let ${k} = ${JSON.stringify(v)}`);
  else if (Number.isInteger(v)) lines.push(`    static let ${k} = ${v}`);
  else lines.push(`    static let ${k} = ${v}`);
}
lines.push("}", "");
fs.writeFileSync(out, lines.join("\n"));
JS
echo "product.json synced"
