import Foundation

/// Minimal Firebase client over the REST APIs.
///
/// The Xcode project is generated by `generate_project.py`, which writes a
/// pbxproj with no Swift Package support — pulling in the Firebase SDK would
/// mean teaching the generator SPM or moving to XcodeGen. The station only
/// needs three calls (anonymous sign-in, one object upload, one document
/// write), so REST is the smaller change.
///
/// The API key is not a secret: it identifies the project, and access is
/// enforced by the Firestore and Storage rules in infra/firebase/.
enum FirebaseREST {
    struct Config {
        let apiKey: String
        let projectId: String
        let bucket: String

        /// Read from Info.plist so a build can be pointed at another project.
        static func fromBundle() -> Config {
            let info = Bundle.main.infoDictionary ?? [:]
            return Config(
                apiKey: info["FirebaseAPIKey"] as? String ?? "",
                projectId: info["FirebaseProjectId"] as? String ?? "",
                bucket: info["FirebaseStorageBucket"] as? String ?? ""
            )
        }
    }

    struct Session: Codable {
        let idToken: String
        let refreshToken: String
        let localId: String
        let expiresAt: Date
    }

    enum FirebaseError: LocalizedError {
        case http(Int, String)
        case malformedResponse

        /// Staff-facing text. Raw Firebase JSON on a shop wall helps nobody.
        var errorDescription: String? {
            switch self {
            case .malformedResponse:
                return "Unexpected response from the server"
            case let .http(code, _) where code == 401 || code == 403:
                return "This station is not approved yet"
            case let .http(code, _) where (500...599).contains(code):
                return "Server unavailable — will retry"
            case .http:
                return isIdentityGone ? "Re-registering this station…" : "Connection problem — will retry"
            }
        }

        /// The stored credentials refer to an identity the server no longer
        /// has: revoked, deleted, or expired beyond recovery. Recoverable only
        /// by starting over with a fresh identity.
        var isIdentityGone: Bool {
            guard case let .http(_, body) = self else { return false }
            return ["USER_NOT_FOUND", "USER_DISABLED", "TOKEN_EXPIRED", "INVALID_REFRESH_TOKEN"]
                .contains { body.contains($0) }
        }
    }

    private static func send(_ request: URLRequest) async throws -> Data {
        let (data, response) = try await URLSession.shared.data(for: request)
        guard let http = response as? HTTPURLResponse else { throw FirebaseError.malformedResponse }
        guard (200..<300).contains(http.statusCode) else {
            throw FirebaseError.http(http.statusCode, String(data: data, encoding: .utf8) ?? "")
        }
        return data
    }

    private static func jsonRequest(_ url: URL, body: [String: Any], method: String = "POST") throws -> URLRequest {
        var request = URLRequest(url: url)
        request.httpMethod = method
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.httpBody = try JSONSerialization.data(withJSONObject: body)
        return request
    }

    // MARK: - Auth

    /// Anonymous sign-in. The resulting uid *is* the station's identity: the
    /// `csStations/{uid}` document and every capture it uploads hang off it.
    static func signInAnonymously(config: Config) async throws -> Session {
        let url = URL(string: "https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=\(config.apiKey)")!
        let data = try await send(try jsonRequest(url, body: ["returnSecureToken": true]))
        return try session(from: data, idKey: "idToken", refreshKey: "refreshToken", uidKey: "localId")
    }

    static func refresh(config: Config, refreshToken: String) async throws -> Session {
        let url = URL(string: "https://securetoken.googleapis.com/v1/token?key=\(config.apiKey)")!
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue("application/x-www-form-urlencoded", forHTTPHeaderField: "Content-Type")
        request.httpBody = "grant_type=refresh_token&refresh_token=\(refreshToken)".data(using: .utf8)
        let data = try await send(request)
        return try session(from: data, idKey: "id_token", refreshKey: "refresh_token", uidKey: "user_id")
    }

    private static func session(from data: Data, idKey: String, refreshKey: String, uidKey: String) throws -> Session {
        guard let json = try JSONSerialization.jsonObject(with: data) as? [String: Any],
              let idToken = json[idKey] as? String,
              let refreshToken = json[refreshKey] as? String,
              let localId = json[uidKey] as? String else {
            throw FirebaseError.malformedResponse
        }
        let expiresIn = Double(json["expiresIn"] as? String ?? json["expires_in"] as? String ?? "3600") ?? 3600
        return Session(
            idToken: idToken,
            refreshToken: refreshToken,
            localId: localId,
            // Refresh a minute early rather than racing the expiry.
            expiresAt: Date().addingTimeInterval(expiresIn - 60)
        )
    }

    // MARK: - Firestore

    /// Firestore REST wants every value tagged with its type.
    private static func encode(_ value: Any) -> [String: Any] {
        switch value {
        case let v as String: return ["stringValue": v]
        case let v as Bool: return ["booleanValue": v]
        case let v as Int: return ["integerValue": String(v)]
        case let v as Date: return ["timestampValue": ISO8601DateFormatter().string(from: v)]
        default: return ["nullValue": NSNull()]
        }
    }

    static func createDocument(
        config: Config,
        idToken: String,
        collection: String,
        documentId: String,
        fields: [String: Any]
    ) async throws {
        let base = "https://firestore.googleapis.com/v1/projects/\(config.projectId)/databases/(default)/documents"
        let url = URL(string: "\(base)/\(collection)?documentId=\(documentId)")!
        var request = try jsonRequest(url, body: ["fields": fields.mapValues(encode)])
        request.setValue("Bearer \(idToken)", forHTTPHeaderField: "Authorization")
        _ = try await send(request)
    }

    static func patchDocument(
        config: Config,
        idToken: String,
        collection: String,
        documentId: String,
        fields: [String: Any]
    ) async throws {
        let base = "https://firestore.googleapis.com/v1/projects/\(config.projectId)/databases/(default)/documents"
        let mask = fields.keys.map { "updateMask.fieldPaths=\($0)" }.joined(separator: "&")
        let url = URL(string: "\(base)/\(collection)/\(documentId)?\(mask)")!
        var request = try jsonRequest(url, body: ["fields": fields.mapValues(encode)], method: "PATCH")
        request.setValue("Bearer \(idToken)", forHTTPHeaderField: "Authorization")
        _ = try await send(request)
    }

    /// Returns nil when the document does not exist yet.
    static func getDocument(
        config: Config,
        idToken: String,
        collection: String,
        documentId: String
    ) async throws -> [String: Any]? {
        let base = "https://firestore.googleapis.com/v1/projects/\(config.projectId)/databases/(default)/documents"
        var request = URLRequest(url: URL(string: "\(base)/\(collection)/\(documentId)")!)
        request.setValue("Bearer \(idToken)", forHTTPHeaderField: "Authorization")

        let (data, response) = try await URLSession.shared.data(for: request)
        guard let http = response as? HTTPURLResponse else { throw FirebaseError.malformedResponse }
        if http.statusCode == 404 { return nil }
        guard (200..<300).contains(http.statusCode) else {
            throw FirebaseError.http(http.statusCode, String(data: data, encoding: .utf8) ?? "")
        }
        guard let json = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            throw FirebaseError.malformedResponse
        }
        return json["fields"] as? [String: Any]
    }

    // MARK: - Storage

    static func upload(
        config: Config,
        idToken: String,
        objectPath: String,
        fileURL: URL,
        contentType: String = "video/mp4"
    ) async throws {
        let encoded = objectPath.addingPercentEncoding(withAllowedCharacters: .alphanumerics) ?? objectPath
        let url = URL(string: "https://firebasestorage.googleapis.com/v0/b/\(config.bucket)/o?uploadType=media&name=\(encoded)")!
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue(contentType, forHTTPHeaderField: "Content-Type")
        request.setValue("Firebase \(idToken)", forHTTPHeaderField: "Authorization")

        let (data, response) = try await URLSession.shared.upload(for: request, fromFile: fileURL)
        guard let http = response as? HTTPURLResponse else { throw FirebaseError.malformedResponse }
        guard (200..<300).contains(http.statusCode) else {
            throw FirebaseError.http(http.statusCode, String(data: data, encoding: .utf8) ?? "")
        }
    }
}
