import Foundation

/// The station's Firebase identity, baked into the build.
///
/// There is no pairing step and no sign-in screen. The app ships with a
/// long-lived refresh token for one pre-approved station account, generated by
/// `apps/backend/provision-station.mts`, so a phone that is plugged in and on
/// Wi-Fi is authenticated the moment it launches. Staff never see a code, a
/// URL, or a token — they press Start.
///
/// The token lives in StationCredentials.plist, which is gitignored. Anyone
/// holding the IPA can extract it, so treat it as a shared secret for one
/// device: revoke with `npx tsx pair.mts --revoke <uid>` and reprovision.
@MainActor
final class StationConfig: ObservableObject {
    /// Whether this build has usable credentials, and whether the last
    /// authentication attempt worked. `nil` means "not tried yet".
    @Published private(set) var isAuthenticated: Bool?
    @Published private(set) var lastError: String?

    let config = FirebaseREST.Config.fromBundle()

    private let bakedRefreshToken: String
    private let bakedUID: String
    private var session: FirebaseREST.Session?

    static let shared = StationConfig()

    init() {
        let creds = Self.loadCredentials()
        bakedRefreshToken = creds?.refreshToken ?? ""
        bakedUID = creds?.uid ?? ""
        if bakedRefreshToken.isEmpty {
            isAuthenticated = false
            lastError = "This build has no station credentials. Reinstall a provisioned build."
        }
    }

    var uid: String? { bakedUID.isEmpty ? nil : bakedUID }

    /// True once the app has exchanged its refresh token at least once.
    var isReady: Bool { isAuthenticated == true }

    private static func loadCredentials() -> (refreshToken: String, uid: String)? {
        guard let url = Bundle.main.url(forResource: "StationCredentials", withExtension: "plist"),
              let data = try? Data(contentsOf: url),
              let plist = try? PropertyListSerialization.propertyList(from: data, format: nil)
                as? [String: Any],
              let token = plist["StationRefreshToken"] as? String,
              let uid = plist["StationUID"] as? String,
              !token.isEmpty, !uid.isEmpty else { return nil }
        return (token, uid)
    }

    /// A valid ID token, refreshing when the cached one is close to expiry.
    /// Always derived from the baked refresh token, so it works on a factory
    /// reset device with no stored state.
    func idToken() async throws -> String {
        if let session, session.expiresAt > Date() {
            return session.idToken
        }
        guard !bakedRefreshToken.isEmpty else {
            throw FirebaseREST.FirebaseError.malformedResponse
        }
        let refreshed = try await FirebaseREST.refresh(config: config, refreshToken: bakedRefreshToken)
        session = refreshed
        isAuthenticated = true
        lastError = nil
        return refreshed.idToken
    }

    /// Authenticate and report liveness. Called on launch and on the heartbeat,
    /// so the dashboard can tell whether the station is still online.
    func refreshAuthAndPing() async {
        guard !bakedRefreshToken.isEmpty else { return }
        do {
            let token = try await idToken()
            try? await FirebaseREST.patchDocument(
                config: config, idToken: token, collection: "csStations", documentId: bakedUID,
                fields: ["lastSeenAt": Date(), "appVersion": Self.appVersion]
            )
        } catch {
            isAuthenticated = false
            lastError = error.localizedDescription
        }
    }

    static var appVersion: String {
        Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "0"
    }
}
